const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const main=$("main"), side=$("#side"), modal=$("#modal");
const curriculum=[
{name:"Mathematical Foundations",lessons:84,color:"blue",desc:"Build the mathematical language needed to reason about models, optimization and learning.",first:"Vectors & Linear Combinations"},
{name:"Computer Science & Systems",lessons:76,color:"green",desc:"Algorithms, memory, processes, networking and GPU fundamentals.",first:"Big-O and Cost Models"},
{name:"Machine Learning & Deep Learning",lessons:104,color:"violet",desc:"Statistical learning, neural networks, optimization and representation learning.",first:"What a Model Actually Learns"},
{name:"Transformers & Foundation Models",lessons:112,color:"pink",desc:"Attention, tokenization, scaling, pretraining, inference and evaluation.",first:"Self-Attention"},
{name:"Reasoning, Agents & Post-Training",lessons:82,color:"orange",desc:"Preference optimization, RL, tool use, agents and reasoning systems.",first:"Why Preference Optimization Works"},
{name:"AI Systems, Research & Frontier Engineering",lessons:62,color:"cyan",desc:"Distributed training, serving, experimentation and frontier engineering.",first:"Throughput, Latency & Utilization"}
];
const lesson={title:"Vectors & Linear Combinations",domain:"Mathematical Foundations",objective:"Understand a vector as a point, direction and computational object, then predict the effect of linear combinations before calculating them.",steps:["Mental Model","Predict","Derive","Implement","Transfer"]};
let state=JSON.parse(localStorage.getItem("blackpearl-state")||'{"mastery":0,"lessonStep":0,"answered":false,"completed":[]}');
const save=()=>localStorage.setItem("blackpearl-state",JSON.stringify(state));
function setActive(label){$$("aside nav button").forEach(b=>b.classList.toggle("active",b.textContent.toLowerCase().includes(label.toLowerCase())));$$(".mobile-tabs button").forEach(b=>b.classList.toggle("active",b.textContent.toLowerCase().includes(label.toLowerCase())));}
function renderOverview(){main.innerHTML=`
<section class="hero"><div class="hero-copy"><div class="eyebrow">▥ &nbsp; HARD LEARNING MODE</div><div class="journey">Your AI learning journey</div><h1>Build the mind<br>behind the next.</h1><p>Turn AI theory into deep, testable capability through interactive learning, implementation, debugging and research.</p><div class="hero-actions"><button class="primary" data-action="lesson">Continue learning →</button><button class="secondary" data-action="mentor">♙ &nbsp; Meet your mentor</button></div></div></section>
<section class="heading"><div><small>YOUR PROGRESS</small><h2>Learning at a glance</h2></div><em>L${Math.min(6,Math.floor(state.mastery/3)+1)} Foundation</em></section>
<section class="stats"><article><div class="stat-icon blue">▣</div><small>DOMAINS</small><strong>06</strong><p>Math → Frontier</p></article><article><div class="stat-icon green">▤</div><small>LESSONS</small><strong>520</strong><p>Structured curriculum</p></article><article><div class="stat-icon violet">⌁</div><small>DEEP PROJECTS</small><strong>12</strong><p>Build, break, rebuild</p></article><article><div class="stat-icon amber">▥</div><small>MASTERY</small><strong>${state.mastery}%</strong><p>Evidence based</p></article></section>
<section class="heading curriculum-heading"><div><small>CURRICULUM</small><h2>Six learning domains</h2></div><button class="view-all" data-action="curriculum">View all&nbsp; ›</button></section>
<section class="grid">${curriculum.map((d,i)=>`<article class="card" data-domain="${i}"><div class="domain-icon ${d.color}">${["Σ","▱","⌘","◇","♧","⌁"][i]}</div><div class="card-copy"><small>0${i+1} · ${d.lessons} LESSONS</small><h3>${d.name}</h3><p>${d.desc}</p></div><button class="card-arrow">›</button><div class="bar"><i style="width:${Math.max(8,state.mastery/2)}%"></i></div></article>`).join("")}</section>
<section class="mentor"><b>◆</b><div><small>DIGITAL MENTOR</small><h2>Don't just read. Think.</h2><p>Your mentor asks before explaining, probes weak assumptions and adapts difficulty to your evidence.</p></div><button class="secondary" data-action="mentor">Enter mentor →</button></section>`;
}
function renderCurriculum(){main.innerHTML=`<section class="page-head"><small>CURRICULUM ENGINE</small><h1>Learn by building evidence.</h1><p>Each domain moves from intuition to implementation, debugging, transfer and research. Nothing is counted as mastered because it was merely read.</p></section><section class="domain-list">${curriculum.map((d,i)=>`<article class="domain-row"><div class="domain-index">${String(i+1).padStart(2,"0")}</div><div><small>${d.lessons} LESSONS</small><h2>${d.name}</h2><p>${d.desc}</p><span class="lesson-tag">Next: ${d.first}</span></div><button class="primary" data-domain="${i}">Open domain →</button></article>`).join("")}</section>`;}
function renderMentor(){main.innerHTML=`<section class="page-head"><small>MENTOR ENGINE</small><h1>Think first. Get help second.</h1><p>The mentor does not immediately reveal the answer. It diagnoses whether the gap is conceptual, mathematical, implementation or transfer-related.</p></section><section class="mentor-console"><div class="mentor-console-top"><span class="eyebrow">LIVE DIAGNOSTIC</span><span class="mentor-status">● READY</span></div><h2>What should happen if we multiply a vector by 0.5?</h2><p class="mentor-question">Don't calculate yet. Describe what changes geometrically.</p><textarea id="mentorAnswer" placeholder="Explain your reasoning in your own words..."></textarea><button class="primary" data-action="mentor-check">Submit reasoning →</button><div id="mentorFeedback"></div></section>`;}
function renderLesson(){const s=lesson.steps[state.lessonStep];main.innerHTML=`<section class="lesson-shell"><div class="lesson-top"><button class="back" data-action="overview">← Dashboard</button><span>MATHEMATICAL FOUNDATIONS · LESSON 01</span></div><div class="lesson-progress"><i style="width:${((state.lessonStep+1)/lesson.steps.length)*100}%"></i></div><div class="lesson-grid"><article class="lesson-main"><small>STEP ${state.lessonStep+1} OF ${lesson.steps.length}</small><h1>${lesson.title}</h1><div class="step-pill">${s}</div>${lessonBody(s)}</article><aside class="lesson-rail"><small>LEARNING OBJECTIVE</small><p>${lesson.objective}</p><hr><small>MASTERY SIGNALS</small><ul><li>Predict before calculating</li><li>Explain the mechanism</li><li>Transfer to a new case</li></ul></aside></div></section>`;}
function lessonBody(step){if(step==="Mental Model")return`<div class="concept"><h2>A vector is more than a list of numbers.</h2><p>In a two-dimensional space, <b>v = [3, 2]</b> can be viewed as a location, a direction with magnitude, or a compact representation that an algorithm can transform.</p><div class="equation">v = [3, 2] &nbsp;&nbsp;→&nbsp;&nbsp; 2v = [6, 4]</div></div><button class="primary lesson-next" data-action="next">I understand the model →</button>`;
if(step==="Predict")return`<div class="concept"><h2>Predict before you calculate.</h2><p>If <b>v = [4, 6]</b>, what should happen when we multiply it by <b>0.5</b>?</p><div class="choice-grid"><button data-choice="same">It stays the same</button><button data-choice="half">Every component becomes half</button><button data-choice="rotate">It rotates 90°</button><button data-choice="zero">It becomes zero</button></div><div id="choiceFeedback"></div></div>`;
if(step==="Derive")return`<div class="concept"><h2>Derive the operation.</h2><p>Scalar multiplication distributes over every coordinate. Write the transformation for <b>a·[x,y]</b>.</p><input id="derive" class="answer" placeholder="e.g. [ax, ay]"><button class="primary lesson-next" data-action="derive-check">Check derivation →</button><div id="deriveFeedback"></div></div>`;
if(step==="Implement")return`<div class="concept"><h2>Implementation checkpoint.</h2><p>Before using a library, describe the smallest function that performs scalar multiplication.</p><pre class="codebox">function scale(v, a) {\n  // return a new vector\n}</pre><textarea id="impl" class="answer area" placeholder="Describe the algorithm or write pseudocode..."></textarea><button class="primary lesson-next" data-action="impl-check">Submit implementation →</button><div id="implFeedback"></div></div>`;
return`<div class="concept"><h2>Transfer the idea.</h2><p>A model layer receives a hidden representation <b>h</b>. Why might scaling a representation change the model's downstream behavior even though its direction is unchanged?</p><textarea id="transfer" class="answer area" placeholder="Reason it out. There is more than one defensible answer."></textarea><button class="primary lesson-next" data-action="transfer-check">Submit transfer reasoning →</button><div id="transferFeedback"></div></div>`;}
function renderProjects(){main.innerHTML=`<section class="page-head"><small>PROJECT LADDER</small><h1>Turn knowledge into systems.</h1><p>Projects increase in scope from micro experiments to research-grade engineering.</p></section><section class="project-grid">${["Vector playground","Backprop from scratch","Tiny Transformer","Attention profiler","Preference optimization lab","Distributed training harness"].map((x,i)=>`<article class="project-card"><small>PROJECT 0${i+1}</small><h2>${x}</h2><p>${["Hours","1–2 days","3–5 days","1 week","2–3 weeks","Capstone"][i]} · evidence driven</p><button class="secondary">Open brief →</button></article>`).join("")}</section>`;}
function renderInterview(){main.innerHTML=`<section class="page-head"><small>INTERVIEW ARENA</small><h1>Explain it under pressure.</h1><p>Questions progress from definitions to derivations, debugging, system design and research follow-ups.</p></section><section class="arena"><div><span>QUESTION 01</span><h2>Why does gradient descent need a learning rate?</h2><p>Answer without using the phrase “because it controls how fast we learn.” Explain the mechanism.</p></div><textarea class="answer area" placeholder="Your answer..."></textarea><button class="primary">Start evaluation →</button></section>`;}
function renderResearch(){main.innerHTML=`<section class="page-head"><small>RESEARCH LAB</small><h1>Turn uncertainty into experiments.</h1><p>Capture hypotheses, variables, baselines, ablations and failure analysis before claiming an improvement.</p></section><section class="research-board"><article><small>HYPOTHESIS</small><h2>What do you believe?</h2><textarea class="answer area" placeholder="State a falsifiable hypothesis..."></textarea></article><article><small>EXPERIMENT</small><h2>How would you test it?</h2><textarea class="answer area" placeholder="Define baseline, variables and measurement..."></textarea></article></section>`;}
function navigate(label){setActive(label);if(label==="Overview")renderOverview();else if(label==="Curriculum")renderCurriculum();else if(label==="Mentor")renderMentor();else if(label==="Projects")renderProjects();else if(label==="Interview Arena")renderInterview();else if(label==="Research Lab")renderResearch();else renderOverview();window.scrollTo({top:0,behavior:"smooth"});}
function feedback(id,msg,good=true){const e=$(id);if(e)e.innerHTML=`<div class="feedback ${good?"good":"coach"}">${msg}</div>`;}
document.addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(b){const a=b.dataset.action;if(a==="lesson"){setActive("Overview");renderLesson()}if(a==="mentor"){navigate("Mentor")}if(a==="curriculum"){navigate("Curriculum")}if(a==="overview"){navigate("Overview")}if(a==="next"){state.lessonStep=Math.min(lesson.steps.length-1,state.lessonStep+1);save();renderLesson()}if(a==="mentor-check"){const v=$("#mentorAnswer")?.value.toLowerCase()||"";feedback("#mentorFeedback",v.includes("half")||v.includes("magnitude")||v.includes("length")?"Good. You identified the key geometric effect: scaling changes magnitude while preserving direction for a positive scalar.":"Push further: what happens to magnitude, direction and each coordinate?",v.includes("half")||v.includes("magnitude"))}if(a==="derive-check"){const v=$("#derive")?.value.replace(/\s/g,"").toLowerCase()||"";const ok=v.includes("ax")&&v.includes("ay");feedback("#deriveFeedback",ok?"Correct. Scalar multiplication distributes coordinate-wise.":"Not yet. Start from a·[x,y] and apply the scalar to each component.",ok);if(ok){state.mastery=Math.min(100,state.mastery+5);save()}}if(a==="impl-check"){const v=$("#impl")?.value||"";feedback("#implFeedback",v.length>20?"Good. You described an actual transformation rather than relying on a library call.":"Give the algorithm: iterate through components, multiply each by the scalar, return a new vector.",v.length>20);if(v.length>20){state.mastery=Math.min(100,state.mastery+5);save()}}if(a==="transfer-check"){const v=$("#transfer")?.value||"";feedback("#transferFeedback",v.length>30?"Strong transfer attempt. Consider separating direction, magnitude and the effect on downstream dot products or activations.":"Make one causal chain: scaling → representation statistics → downstream operation → output.",v.length>30);if(v.length>30){state.mastery=Math.min(100,state.mastery+5);save()}}}});
document.addEventListener("click",e=>{const c=e.target.closest("[data-choice]");if(!c)return;$$("[data-choice]").forEach(x=>x.classList.remove("selected"));c.classList.add("selected");const ok=c.dataset.choice==="half";const el=$("#choiceFeedback");if(el)el.innerHTML=`<div class="feedback ${ok?"good":"coach"}">${ok?"Correct. Scalar multiplication scales every component, so [4,6] becomes [2,3].":"Check the operation coordinate by coordinate. What happens to x? What happens to y?"}</div>`;if(ok){state.mastery=Math.min(100,state.mastery+5);state.answered=true;save();setTimeout(()=>{state.lessonStep=2;save();renderLesson()},650)}});
$("#menu").onclick=()=>side.classList.toggle("open");
$("#theme").onclick=()=>document.documentElement.classList.toggle("dark");
$("#search").onclick=()=>modal.classList.add("open");
$("#close").onclick=()=>modal.classList.remove("open");
modal.onclick=e=>{if(e.target===modal)modal.classList.remove("open")};
$$("aside nav button").forEach(b=>b.onclick=()=>navigate(b.textContent.trim().includes("Interview")?"Interview Arena":b.textContent.trim().includes("Research")?"Research Lab":b.textContent.trim().includes("Curriculum")?"Curriculum":b.textContent.trim().includes("Mentor")?"Mentor":b.textContent.trim().includes("Projects")?"Projects":b.textContent.trim().includes("Settings")?"Settings":"Overview"));
document.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();modal.classList.add("open");$("#q").focus()}if(e.key==="Escape")modal.classList.remove("open")};
renderOverview();